### PR TITLE
Tweak eval scale

### PR DESCRIPTION
**Pull request by lucametehau**
Bench: 3474718

### CODE REVIEW

**Comment by tissatussa** [comment]
i see many eval UCI options .. so these are tweaked ? Did you use a tool like OpenBench for that and many self play games ? As far as i understand, this is a common method.

**Comment by lucametehau** [comment]
Hi there!
The UCI options are basically all of the search constants used in Clover's search, so if you tweak them, you'll get another Clover =).
They are there so that I can easily tune them when needed or for other people that try out Clover and want to see other behaviour. For tweaking them, I used [Weather-factory](https://github.com/jnlt3/weather-factory). After using this tool, the changes are, of course, tested by SPRT.

**Comment by tissatussa** [comment]
thanks for your info and confirmation.

i'm not a programmer of any engine (yet) and i'm not familiar with SPRT, so i Googled it and found a nice article https://tearth.dev/posts/a-few-thoughts-about-testing-chess-engines/ which states :

_.. about a method which is widely used to test changes: Sequential Probability Ratio Test (SPRT) [..] don’t trust self-plays, gauntlets give a much better impression how some code change influenced the engine’s strength [..] see https://rustic-chess.org/progress/sprt_testing.html .._

do you agree with this approach ?  I guess not ..

**Comment by lucametehau** [comment]
Well, of course I agree with SPRT testing, since I use an OpenBench instance, which uses Cutechess in its background, which uses SPRT to check for which engine is better =). The article is very good btw. As for gauntlets, I don't rly run them, I just take self-play elo I gained and approximate that real elo is 50-70% of self-play elo. Hope this helps a bit!

**Comment by tissatussa** [comment]
regarding CuteChess CLI : i used it, but not often, mostly i use the GUI .. running tournaments in CLI for testing seems a good idea .. i'm wondering : could an analysis be made of a chess game, like we can do on lichess.org (even with eval graph!) ? Just set a fixed depth or time for each move and let a choosen engine build the output .. which arguments should be given to achive that ?

**Pull request merged**
